document.addEventListener("DOMContentLoaded", () => {
  // Configs
  const GITHUB_USERNAME = "2902Duy";
  
  // DOM Elements
  const projectsGrid = document.getElementById("projects-grid");
  const coauthorsList = document.getElementById("coauthors-list");
  
  // Initialize
  fetchGitHubRepos();
  fetchCoauthors();
  
  /**
   * Fetches public repositories from GitHub API
   */
  async function fetchGitHubRepos() {
    try {
      const response = await fetch(`https://api.github.com/users/${GITHUB_USERNAME}/repos?sort=updated&per_page=6`);
      
      if (!response.ok) {
        throw new Error(`GitHub API returned status: ${response.status}`);
      }
      
      const repos = await response.json();
      
      // Filter out the profile README repository and sort by push date
      const filteredRepos = repos
        .filter(repo => repo.name.toLowerCase() !== GITHUB_USERNAME.toLowerCase())
        .slice(0, 6); // Take top 6 active repositories
        
      renderRepos(filteredRepos);
    } catch (error) {
      console.error("Error fetching GitHub repos:", error);
      renderReposError();
    }
  }

  /**
   * Renders the repository cards in the UI
   */
  function renderRepos(repos) {
    projectsGrid.innerHTML = "";
    
    if (repos.length === 0) {
      projectsGrid.innerHTML = `
        <div class="card" style="grid-column: 1/-1; text-align: center; padding: 3rem;">
          <p class="card-desc">No public repositories found.</p>
        </div>
      `;
      return;
    }
    
    repos.forEach(repo => {
      const card = document.createElement("a");
      card.href = repo.html_url;
      card.target = "_blank";
      card.className = "card";
      card.setAttribute("aria-label", `Repository ${repo.name}: ${repo.description || 'No description'}`);
      
      // Determine language and dot class
      const language = repo.language || "Unknown";
      const langClass = `lang-${language.toLowerCase().replace(/[+#]/g, "")}`;
      
      // Format updated date
      const updatedDate = new Date(repo.updated_at).toLocaleDateString("en-US", {
        month: "short",
        day: "numeric",
        year: "numeric"
      });
      
      card.innerHTML = `
        <div>
          <div class="card-title">
            <svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg">
              <path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z"></path>
            </svg>
            ${repo.name}
          </div>
          <p class="card-desc">${repo.description || "No description provided."}</p>
        </div>
        <div class="card-meta">
          <div class="card-lang">
            <span class="lang-dot ${langClass}"></span>
            ${language}
          </div>
          <div class="card-stats">
            <div class="card-stat-item" title="Stars">
              <svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg">
                <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon>
              </svg>
              ${repo.stargazers_count}
            </div>
            <div class="card-stat-item" title="Forks">
              <svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg">
                <circle cx="18" cy="18" r="3"></circle>
                <circle cx="6" cy="6" r="3"></circle>
                <circle cx="6" cy="18" r="3"></circle>
                <path d="M18 15V9a4 4 0 0 0-4-4H9"></path>
                <line x1="6" y1="9" x2="6" y2="15"></line>
              </svg>
              ${repo.forks_count}
            </div>
          </div>
        </div>
      `;
      
      projectsGrid.appendChild(card);
    });
  }

  /**
   * Renders error state for repositories
   */
  function renderReposError() {
    projectsGrid.innerHTML = `
      <div class="card" style="grid-column: 1/-1; text-align: center; padding: 3rem; border-color: var(--accent-pink);">
        <p class="card-desc" style="color: var(--accent-pink);">Failed to load repositories from GitHub. Please try again later.</p>
      </div>
    `;
  }

  /**
   * Fetches local coauthors.json generated by Python
   */
  async function fetchCoauthors() {
    try {
      const response = await fetch("./coauthors.json");
      if (!response.ok) {
        throw new Error("Could not load coauthors.json database");
      }
      
      const coauthors = await response.json();
      renderCoauthors(coauthors);
    } catch (error) {
      console.warn("Failed to fetch coauthors.json, rendering fallback:", error);
      renderCoauthorsFallback();
    }
  }

  /**
   * Renders co-authors database list
   */
  function renderCoauthors(coauthors) {
    coauthorsList.innerHTML = "";
    
    if (!coauthors || coauthors.length === 0) {
      renderCoauthorsFallback();
      return;
    }
    
    const wrapper = document.createElement("div");
    wrapper.className = "coauthor-list";
    
    coauthors.forEach(author => {
      const item = document.createElement("div");
      item.className = "coauthor-item";
      
      const firstLetter = author.name.charAt(0).toUpperCase();
      
      item.innerHTML = `
        <div class="coauthor-info">
          <div class="coauthor-avatar-fallback">${firstLetter}</div>
          <div>
            <div class="coauthor-name">${author.name}</div>
            <div class="coauthor-email">${author.email}</div>
          </div>
        </div>
        <div class="coauthor-commits">
          ${author.commits} <span>commits</span>
        </div>
      `;
      
      wrapper.appendChild(item);
    });
    
    coauthorsList.appendChild(wrapper);
  }

  /**
   * Renders fallback visual for co-authors section
   */
  function renderCoauthorsFallback() {
    coauthorsList.innerHTML = `
      <div class="coauthors-fallback">
        <svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" height="48" width="48" xmlns="http://www.w3.org/2000/svg">
          <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
          <circle cx="9" cy="7" r="4"></circle>
          <path d="M23 21v-2a4 4 0 0 0-3-3.87"></path>
          <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
        </svg>
        <p>No registered external co-authors or bots detected yet.</p>
        <p style="font-size: 0.85rem; color: var(--text-sub); margin-top: var(--spacing-sm);">
          All commits are currently authored solely by you. Ready for future collaborative commits!
        </p>
      </div>
    `;
  }
});
